reference_currency: "USD"

process: 
  - execution: daily  # one between (daily, bulk)
  - start_date: 2025-01-01 # format: YYYY-MM-DD (Only for bulk_update)
  - end_date: 2025-01-02 # format: YYYY-MM-DD (Only for bulk_update)

currencies:
  - EUR
  - JPY
  - GBP
  - AUD
  - CAD
  - CHF
  - CNY
  - SEK
  - MXN
  - NZD
  - SGD
  - HKD
  - NOK
  - KRW
  - TRY
  - INR
  - RUB
  - BRL
  - ZAR
  - DKK
  - PLN
  - TWD
  - THB
  - MYR
