"""Currencies target table

Revision ID: b8b9abb0d295
Revises: 
Create Date: 2025-04-04 23:48:48.804524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b9abb0d295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_exchange_rates',
    sa.Column('date_key', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference_currency', sa.String(length=3), nullable=False),
    sa.Column('rate_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_jpy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_gbp', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_aud', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_cad', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_chf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_cny', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_sek', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_mxn', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_nzd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_sgd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_hkd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_nok', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_krw', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_try', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_inr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_rub', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_brl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_zar', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_dkk', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_pln', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_twd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_thb', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_myr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('date_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_exchange_rates')
    # ### end Alembic commands ###
